site_title: Victoria Smus Piano Studio
date_format: '%d %B %Y'
verbs:
  post: 'Published'
  talk: 'Presented'
  link: 'Linked'
permalink_format:
  post: '{{slug}}'
  page: '{{slug}}'
  talk: 'talk/{{year}}/{{slug}}'
  link: 'link/{{year}}/{{slug}}'
  draft: 'drafts/{{slug}}'
  archive: 'archive/{{slug}}'
  feed: '{{slug}}'
  index: ''
